version: 0.0
os: linux
files:
  - source: index.html
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
